services:
  - type: web
    name: online-cres
    env: node
    rootDir: .
    buildCommand: npm run build
    startCommand: npm run start
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      # Render injects PORT automatically. Our server reads process.env.PORT.
      # Add your secrets in the Render Dashboard or uncomment and set them here (not recommended for public repos):
      # - key: DB_HOST
      #   sync: false
      # - key: DB_USER
      #   sync: false
      # - key: DB_PASSWORD
      #   sync: false
      # - key: DB_NAME
      #   sync: false
      # - key: DB_PORT
      #   value: "3306"
      #   sync: false
      # - key: JWT_SECRET
      #   sync: false
      # - key: JWT_EXPIRES_IN
      #   value: 30m
      #   sync: false
      # - key: SMTP_HOST
      #   sync: false
      # - key: SMTP_PORT
      #   value: "587"
      #   sync: false
      # - key: SMTP_USER
      #   sync: false
      # - key: SMTP_PASS
      #   sync: false
      # - key: OTP_EMAIL_FROM
      #   sync: false
      # - key: TOKEN_SALT
      #   sync: false
      # - key: FRONTEND_ORIGIN
      #   value: "" # Not needed for single-service
      #   sync: false
